# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-03 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(help_text='Name of the person having made the comment', max_length=100)),
                ('body', models.TextField(help_text='The body of the comment')),
            ],
        ),
    ]
